version: 2.1

commands:

  "dirty-check":
    steps:
      - run:
          name: "Dirty check"
          command: |
            # On Windows, `git status` doesn't record no-op
            # line-ending changes in to the index, so things show as
            # dirty even if they aren't.  Trying to `add` them does
            # trigger the appropriate index update.  So do a `git add`
            # *before* the `git status --porcelain` to work around
            # Windows being terrible; we'd otherwise put the `git add`
            # inside of the `if` block to help generate better output
            # for `git diff`.
            git add .
            if [[ -n "$(git status --porcelain)" ]]; then
               PAGER= git diff --cached
               exit 1
            fi

jobs:

  "test":
    docker:
    - image: golang:1.15
    resource_class: small
    steps:
    - checkout
    - run: make test
    - run:
        name: "Generate code-coverage report"
        command: |
          set -e
          if test -e dlib.cov; then
            make .circleci/goveralls
            .circleci/goveralls -coverprofile=dlib.cov -service=circle-ci -repotoken=$COVERALLS_TOKEN
          fi
        when: always

  "lint":
    docker:
    - image: golang:1.15
    resource_class: small
    steps:
    - checkout
    - run: make lint

  "generate":
    docker:
    - image: golang:1.15
    resource_class: small
    steps:
    - checkout
    - run: make generate-clean
    - run: make generate
    - dirty-check

workflows:

  "dlib":
    jobs:
    - "test"
    - "lint"
    - "generate"
